# Generated by Django 2.2.18 on 2021-12-28 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('passwords', models.CharField(max_length=300)),
            ],
        ),
    ]
